DROP TABLE IF EXISTS CERTIFICATE;
DROP TABLE IF EXISTS COURSE;
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE CERTIFICATE(
    ID SERIAL PRIMARY KEY,
    VALIDATION_CODE VARCHAR UNIQUE,
    STUDENT_ID INTEGER REFERENCES STUDENT(ID) ON DELETE CASCADE,
    COURSE_ID INTEGER REFERENCES COURSE(ID) ON DELETE CASCADE,
    CREATED_DATE DATE,
    LAST_MODIFIED_DATE DATE
);


CREATE TABLE STUDENT(
    ID SERIAL PRIMARY KEY,
    FIRSTNAME VARCHAR,
    LASTNAME VARCHAR,
);


CREATE TABLE COURSE(
    ID SERIAL PRIMARY KEY,
    INSTITUTION_NAME INTEGER,
    TITLE VARCHAR,
    DURATION NUMBER,
);